name: Rails CI/CD

on:
 push:
   branches: [ master ]
 pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version

      - name: Install dependencies
        run: bundle install

      - name: Run rubocop (Linitng)
        run: bundle exec rubocop

      - name: Run brakeman (code smells)
        run: bundle exec brakeman

      - name: Run tests
        run: bundle exec rails test